<?php

/**
 * @file
 * Contains simple_stock_normal.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simple_stock_normal_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simple_stock_normal module.
    case 'help.page.simple_stock_normal':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_base_field_info().
 * @throws \Drupal\Component\Plugin\Exception\PluginException
 */
function simple_stock_normal_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  /** @var Drupal\simple_stock\Plugin\StockTypeManager $stock_type_manager */
  $stock_type_manager = \Drupal::getContainer()->get('plugin.manager.stock_type');
  /** @var Drupal\simple_stock\Plugin\StockTypeInterface $stock_type */
  $stock_type = $stock_type_manager->createInstance('normal');
  if ($stock_type->supportEntityType($entity_type)) {
    $fields = $stock_type->stockBaseFieldDefinitions() + $fields;
  }

  return $fields;
}


/**
 * Implements hook_entity_type_alter().
 */
function simple_stock_normal_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entity_types['commerce_product_variation']->setListBuilderClass('Drupal\simple_stock_normal\ProductVariationListBuilder');
}
