<?php

/**
 * @file
 * Contains simple_stock_fixed.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simple_stock_fixed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simple_stock_fixed module.
    case 'help.page.simple_stock_fixed':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_base_field_info().
 * @throws \Drupal\Component\Plugin\Exception\PluginException
 */
function simple_stock_fixed_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  /** @var Drupal\simple_stock\Plugin\StockTypeManager $stock_type_manager */
  $stock_type_manager = \Drupal::getContainer()->get('plugin.manager.stock_type');
  $stock_type = $stock_type_manager->createInstance('fixed');
  if ($stock_type->supportEntityType($entity_type)) {
    $fields = $stock_type->stockBaseFieldDefinitions() + $fields;
  }

  return $fields;
}